### ISSUE TITLE
Remove `concepts.ring2.abstractcrossreference`

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/People#18]
Shouldn't the handler that is mapped to `concepts.ring2.abstractcrossreference` be mapped to Simplified chat attachment?

https://github.com/StarcounterSamples/People/blob/a13de89b8d2da36dd6f2b55e7334cc538d9d818d/src/People/Api/OntologyMap.cs

**Comment by miyconst** [comment]
Yes, it should be. Fixed now.
