### ISSUE TITLE
Standalone mode does not work

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/People#19]
Standalone mode does not work. The error in console:

> Uncaught TypeError: Polymer.dom.addDebouncer is not a function
> Uncaught TypeError: Polymer.dom is not a function

See screenshot:

<img width="1456" alt="screenshot 2015-10-08 12 03 48" src="https://cloud.githubusercontent.com/assets/566463/10363425/b9437bd8-6db4-11e5-93b0-f4e0d67e21cd.png">

This might be because wrong order of declaration. 

Compare People (doesn't work):

```html
    <link rel="import" href="/sys/polymer/polymer.html" />
    <script src="/sys/webcomponentsjs/webcomponents.js"></script>
    <script>
        window.Polymer = window.Polymer || {};
        window.Polymer.dom = "shadow";
    </script>

```

with Launcher (works):

```html
    <script src="/sys/webcomponentsjs/webcomponents.js"></script>
    <script>
        window.Polymer = window.Polymer || {};
        window.Polymer.dom = "shadow";
    </script>
    <link rel="import" href="/sys/polymer/polymer.html" />
```

But should `Polymer.dom` should be string at all? In Polymer (see screenshot above) it is used as an object.

**Comment by warpech** [comment]
Explained here: https://www.polymer-project.org/1.0/docs/devguide/settings.html

**Comment by warpech** [comment]
@miyconst could you do it?

**Comment by miyconst** [comment]
Yes, the issue was because of wrong order. Fixed now.
