### ISSUE TITLE
Remove dom-bind-notifier, no longer needed

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/People#24]

**Comment by miyconst** [comment]
The `dom-bind-notifier` is now removed. Apart from this I also refactored some parts:

- Cleaned up client side javascript.
- Implemented usage of standalone mode.
- Removed check "whether app is in launcher" by checking `Session.Current == null`.

Right now Standalone and InLauncher mode shares the same master page. The pages has a menu section, the section is wrapped into a `<template is="dom-if" if="{{model.ShowMenu}}">`. The `model.ShowMenu` is set to `false` as soon as partial handler for menu section is called, which means someone else is displaying the app menu.

**Comment by warpech** [comment]
> The pages has a menu section, the section is wrapped into a <template is="dom-if" if="{{model.ShowMenu}}">. The model.ShowMenu is set to false as soon as partial handler for menu section is called, which means someone else is displaying the app menu.

Clever pattern!
