### ISSUE TITLE
Add custom fields to the People app (PersonPage)

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/People#33]
I would like to define custom fields, such as:
- GitHub username
- Skype ID

It should be possible to add one or more custom fields to a Person.

**Comment by warpech** [comment]
cc @chrhol

**Comment by warpech** [comment]
There should be a new button at the top of the Person's page: "Add custom field".

A person can have multiple custom fields.

A custom field consists of:
- type (selectable from the autocomplete - or editable, when you want to write a new)
- value

The data model and view-model can be inspired by EmailAddress.

**Comment by Joltrix** [comment]
Implemented in PR #40

**Comment by warpech** [comment]
Closing as done
