### ISSUE TITLE
The viewmodel for the element types (addresses, emails, phonenumbers, custom elements) is not working

### ISSUE THREAD

**Issue by Joltrix** [StarcounterSamples/People#37]
The code for everything works, and they are assigned their "value" (for the `<select>` tag, and they update accordingly). However, the view-model does not update correctly. And always displays the first type in that specific items list.

I asked @miyconst about it, and he said that it was a known issue caused by Polymer adding the `<option>`s after it has declared the selected-index, thus always displaying the first item in the list.

/cc @warpech

**Comment by warpech** [comment]
Could you check if switching to `<juicy-select>` fixes the problem?

**Comment by miyconst** [comment]
Please note that `<juicy-select>` does not support `selected-index`, but work properly with `value` binding.

**Comment by Joltrix** [comment]
Yeah, i remember you telling me that yesterday :), Thank you!

**Comment by Joltrix** [comment]
cc @warpech 

Yes, juicy-select works. I managed to fix it for the custom elements. Should i fix it for the remaining "elements" as well, while I'm at it? (address, email, phonenumber)

**Comment by Joltrix** [comment]
Implemented in PR #43

**Comment by warpech** [comment]
Closing as fixed.
