### ISSUE TITLE
OrganizationPerson missing reference

### ISSUE THREAD

**Issue by ubbeK** [StarcounterSamples/People#46]
### Steps to reproduce
pull the latest from People repository
run build.nat

### Expected result
msbuild to compile the solution with 0 warnings and 0 errors

### Actual result

```
"C:\GitHub\StarcounterSamples\People\src\People\People.csproj" (default target) (1) ->
(CoreCompile target) ->
  ViewModels\OrganizationPersonPage.json.cs(7,57): error CS0246: The type or namespace name 'OrganizationPerson' could not be found (are you missing a using directive or an assembly reference?) [C:\GitHub\StarcounterSamples\People\src\People\People.csproj]
  Helpers\OrganizationsProvider.cs(32,32): error CS0246: The type or namespace name 'OrganizationPerson' could not be found (are you missing a using directive or an assembly reference?) [C:\GitHub\StarcounterSamples\People\src\People\People.csproj]
  obj\x64\Debug\ViewModels\OrganizationPersonPage-2.json.g.cs(66,16): error CS0246: The type or namespace name 'OrganizationPerson' could not be found (are you missing a using directive or an assembly reference?) [C:\GitHub\StarcounterSamples\People\src\People\People.cs
proj]

    0 Warning(s)
    3 Error(s)
```

**Comment by ubbeK** [comment]
@warpech @alemoi Doesn't our CI server compile each StarcounteSample/repository after each commit?

**Comment by alemoi** [comment]
Here is the list of current repositories we build (People is not there as you see):
```
https://github.com/starcounter/pokerdemo.git %git_pokerdemo_branch% %sc_run_pokerdemo_test%
https://github.com/StarcounterPrefabs/Launcher.git %git_launcher_branch% %sc_run_store_apps_test%
https://github.com/starcountersamples/products.git master %sc_run_store_apps_test%
https://github.com/starcountersamples/barcodes.git master %sc_run_store_apps_test%
https://github.com/starcountersamples/skyper.git master %sc_run_store_apps_test%
https://github.com/starcountersamples/images.git master %sc_run_store_apps_test%
https://github.com/starcountersamples/signin.git master %sc_run_store_apps_test%
https://github.com/starcounter/tpc-a.git master %run_tpca_test%
https://github.com/starcountersamples/kitchensink.git %git_kitchensink_branch% %run_kitchensink_selenium_test%
```
However this list would be cleaned up soon, since it was decided to separate Starcounter builds from Apps builds. So none apps would be automatically build by terms of Starcounter "core" build system.

**Comment by warpech** [comment]
People app `develop` branch should build well. Please check if that branch builds for you. If yes, then it should be merged to `master`

**Comment by ubbeK** [comment]
`However this list would be cleaned up soon, since it was decided to separate Starcounter builds from Apps builds. So none apps would be automatically build by terms of Starcounter "core" build system.`

That is fine. But do we have resources to set up jobs for each SampleApp for each commit with latest starcounter Version?

> People app develop branch should build well. Please check if that branch builds for you. If yes, then it should be merged to master

I'll try it out

**Comment by ubbeK** [comment]
@warpech develop branch works fine. Should I merge it?

**Comment by ubbeK** [comment]
> @ubbeK Please check if that branch builds for you. If yes, then it should be merged to master

@warpech: Everything works well, will merge it now.

**Comment by ubbeK** [comment]
Develop branch is [merged](https://github.com/StarcounterSamples/People/commit/1a674995e327403bc22c2e515f210bb69501dbea), closing issue

**Comment by warpech** [comment]
Great, thanks

**Comment by warpech** [comment]
> That is fine. But do we have resources to set up jobs for each SampleApp for each commit with latest starcounter Version?

Yes, this process has been started by @joozek78 and is tracked here: https://github.com/Starcounter/AdminTrack/issues/44
