### ISSUE TITLE
HTML Element's ids are not namespaced with app name

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/People#50]
### Steps to reproduce
1. Run Launcher
2. Run People app
3. Go to any people page like [/people](http://localhost:8080/people)
4. type into console `document.querySelector('#body')`

### Expected result
`null`
### Actual result
`<div id="body" slot="People/0">...</div>`

### Technical information
`StandalonePage.html` is used not only in standalone mode, therefore classes, ids and styles used there will be used also in Launcher
https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/StandalonePage.html#L19

##### Involved apps' version

 - StarcounterPrefabs/Launcher@0f9268340de60fc88bb021a8387e9a5664ebe5a2
 - StarcounterSamples/People@f27cebe9c7d443329b6a56039461cfe2de8ee36c
 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] IE 11
- [?] Safari 9
- [?] Safari 8

## notes

- I would suggest bemifying CSS selectors,
- include standalone stylesheet only in standalone mode - for example by moving it inside `dom-if`,
- removing `<div id="body"`> and attaching (BEMified) classname directly to the `<starcounter-include>`

**Comment by warpech** [comment]
Solution, change ids to BEM class names:

```
#body -> .people-body
#top-menu -> .people-top-menu
etc
```

More about BEM class names in Starcounter apps: https://docs.starcounter.io/guides/mapping-and-blending/avoiding-css-conflicts.html

This also fixes: https://github.com/StarcounterSamples/People/issues/22 (should be done in the same PR)

**Comment by warpech** [comment]
@threezool could you please take it? Please get familiar with the Guidelines (editable as a GitHub repo), especially the branching page and C# coding style.

**Comment by threezool** [comment]
Fixed in #62

**Comment by warpech** [comment]
LGTM

**Comment by warpech** [comment]
The previous solution was reverted. New solution tracked in PR #65

**Comment by warpech** [comment]
Closing as done.
