### ISSUE TITLE
Remove unused html imports

### ISSUE THREAD

**Issue by mmnosek** [StarcounterSamples/People#54]
I found at least one - at PersonsPage. There is an import at the top, but it is not used at all.

**Comment by warpech** [comment]
@threezool could you please take it? Please get familiar with the Guidelines (editable as a GitHub repo), especially the branching page and C# coding style.

**Comment by warpech** [comment]
@un-tone could you please take it?

**Comment by un-tone** [comment]
Crated PR https://github.com/StarcounterSamples/People/pull/71

**Comment by un-tone** [comment]
Closing as done
