### ISSUE TITLE
How to add custom fields

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/People#58]
### Steps to reproduce
1. Clone/install the app
2. Run it
3. Go to http://localhost:8080/people/persons/add
4. Click "Add custom field"
5. [ ] There is no value to choose
6. Go to http://localhost:8080/people/persons/
7. Click "Custom fields selection"
8. [ ] There is no value to choose
9. Go to https://github.com/StarcounterSamples/People to find a way

### Expected result
There should be some way to define custom fields, and it should be described in README

### Actual result
I was not able to find any way.

##### Involved apps' version

- People -https://github.com/StarcounterSamples/People/tree/58e72729b35a5b740384ceb3ecdafd22f0a84049 (develop)
- Launcher - https://github.com/StarcounterPrefabs/Launcher/tree/8fc5009bb7ad26389af0077824ef66fe1fd2fafe (develop)
 
##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

//cc @Joltrix

**Comment by tomalec** [comment]
Sorry, my bad, I can simply type it into the combo box 😶

**Comment by Joltrix** [comment]
Haha yeah, maybe not the most intuitive way of adding custom classes... xD Perhaps we should write about that in the README
