### ISSUE TITLE
Listing persons: make sense to be able to view a person?

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterSamples/People#59]
Just reflected when at /people/persons of our very own insider app. I wanted to see some detail of a user. Clicking the name would be the most intuitive to me. Instead I had to use [Edit].

**Comment by warpech** [comment]
Good suggestion!

@threezool could you please take it? Please get familiar with the [Guidelines](https://starcounter.gitbooks.io/guidelines/content/) (editable as a [GitHub repo](https://github.com/StarcounterPrefabs/Guidelines)), especially the branching page and C# coding style.

**Comment by threezool** [comment]
Fixed in 3b482283c3cf3faa3ca72e1ca5f7a212239ccb7c

**Comment by warpech** [comment]
Please see the comment: https://github.com/StarcounterSamples/People/commit/3b482283c3cf3faa3ca72e1ca5f7a212239ccb7c

**Comment by warpech** [comment]
Commit https://github.com/StarcounterSamples/People/commit/3b482283c3cf3faa3ca72e1ca5f7a212239ccb7c needs reverting. The solution is tracked in PR #64

**Comment by warpech** [comment]
Reverted commit  https://github.com/StarcounterSamples/People/commit/3b482283c3cf3faa3ca72e1ca5f7a212239ccb7c because no response from @threezool. The correct solution is still in progress in PR #64

**Comment by warpech** [comment]
Closing as done. PR #64 was merged to `develop`.
