### ISSUE TITLE
Branches have diverged

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/People#63]
@threezool could you please merge your changes from `master` to `develop`?

**Comment by threezool** [comment]
Sure, synced the dev branch and changed to it so not to affect the master branch.

**Comment by warpech** [comment]
Not fixed yet... https://github.com/StarcounterSamples/People/commit/e09579cde1cf157ec5253d6df9e8837c5931148a was reverted but `master` branch still needs to be merged to `develop`, because `develop` is two commits behind:

<img width="931" alt="screen shot 2017-01-30 at 15 32 15" src="https://cloud.githubusercontent.com/assets/566463/22426875/51fa4b92-e701-11e6-8a89-13074ba5bacf.png">

**Comment by warpech** [comment]
This is fixed now, thanks!
