### ISSUE TITLE
Improve the look of pagination

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/People#68]
### Steps to reproduce

1. Start People app `develop` branch
2. Start Launcher app `develop` branch
3. Start SignIn app `develop` branch
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/content/dynamic/apps`
6. Sign in as admin user
7. Click on "People" in the menu

### Expected result

The page should look nicer. My proposal:

- the dropdown that now shows `5` should be changed to say `Show 5 items per page` and moved to the bottom of the page
- the buttons that say `<<`, `<`, `>`, `>>` should be changed to `First`, `Previous`, `Next`, `Last`
- the information about the number of pages should be moved to the same line as the buttons

![artboard](https://cloud.githubusercontent.com/assets/566463/22661040/184a095c-eca4-11e6-8601-da55da25a0ae.png)

The styling of this should be done in `starcounter-composition`.

The same applies to both People list and Organisations list.

### Actual result

The page looks quite messy. 

![2017-02-06 19_35_17-people](https://cloud.githubusercontent.com/assets/566463/22661044/1fcabdde-eca4-11e6-843e-99acf7b61540.png)

##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

**Comment by warpech** [comment]
@un-tone can you pls take this?

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterSamples/People/pull/72

**Comment by un-tone** [comment]
Closing as done.
